---

- name: Create a network
  gcp_compute_network:
    name: "gitlab-network"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: network

- name: Internal/external firewall rules
  gcp_compute_firewall:
    name: "internal-external-rules"
    allowed:
      - ip_protocol: tcp
        ports:
          - 22
          - 80
          - 5601
          - 443
          - 2222
          - 8080
      - ip_protocol: icmp
    network: 
      name: "global/networks/{{ network.name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present

- name: Internal firewall rules
  gcp_compute_firewall:
    name: "internal-rules"
    allowed:
      - ip_protocol: tcp
        ports:
          - 5432
          - 5000
          - 5601
          - 8075
          - 9200
          - 5044
          - 26379
          - 6379
          - 443
          - 8080
      - ip_protocol: 112
    source_ranges:
      - 10.0.0.0/8
    network:
      name: "global/networks/{{ network.name }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
